### ISSUE TITLE
First Time Use, permission errors during initializing a new project.

### ISSUE THREAD

**Issue by jeremysadkins** [Abe404/root_painter#130]
**Describe the bug**
I am trying to set up RootPainter, and I am at the point where I am trying to create a new project. I am set up using SSHFS and a mapped folder from my University's computing cluster. It seems like RootPainter has writing access, but something further along is going wrong with permissions.

**To Reproduce**

**Expected behavior**
I expected the program to initialize.

**Screenshots**
![image](https://github.com/Abe404/root_painter/assets/86312645/414caf29-a05e-4dfa-9efd-46f798af3d3d)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10, Ubuntu 20 etc]
 - Browser (if related to the colab notebook) [e.g. chrome, safari]
 - Version: 1.18.3181.0

**Additional context**

[Initialising RootPainter Error.txt](https://github.com/Abe404/root_painter/files/14145688/Initialising.RootPainter.Error.txt)

**Comment by Abe404** [comment]
Looks like a problem with your network drive. You might need to talk to someone from your I.T department (or whoever helps you set up network drives) to figure out how to get write access.

It also looks like you've specified your sync directory as you root folder or Y:\\

You may have more luck with permissions if you specify the sync directory to be inside your user home folder. I'm not sure exactly what the best solution is but its related to the specifics of you file system and sshfs settings. I think you could either try altering permissions/settings or specify a different folder where the current user does have write access.

**Comment by jeremysadkins** [comment]
I got it up and running with our university cluster. Thank you!
