### ISSUE TITLE
Fail to install Rootpainter on my local pc.

### ISSUE THREAD

**Issue by ExtroT** [Abe404/root_painter#141]
Hi, 

Thank you for your time! 
I am facing issues when trying to install Rootpainter locally. The full error is provided below. 

Tony

**Desktop:**
 - OS: windows 11
 - anaconda prompt

(base) D:\root_painter> pip install root-painter-trainer
Collecting root-painter-trainer
  Using cached root_painter_trainer-0.2.27.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting scikit-image==0.19.3 (from root-painter-trainer)
  Using cached scikit-image-0.19.3.tar.gz (22.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.24.2 (from root-painter-trainer)
  Using cached numpy-1.24.2-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting scipy==1.10.0 (from root-painter-trainer)
  Using cached scipy-1.10.0-cp311-cp311-win_amd64.whl.metadata (58 kB)
Collecting Pillow==9.3.0 (from root-painter-trainer)
  Using cached Pillow-9.3.0-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Collecting imagecodecs==2021.8.26 (from root-painter-trainer)
  Using cached imagecodecs-2021.8.26.tar.gz (10.4 MB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of root-painter-trainer to determine which version is compatible with other requirements. This could take a while.
Collecting root-painter-trainer
  Using cached root_painter_trainer-0.2.25.3.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
  Using cached root_painter_trainer-0.2.25.2.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
  Using cached root_painter_trainer-0.2.25.1.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.23.3 (from root-painter-trainer)
  Using cached numpy-1.23.3-cp311-cp311-win_amd64.whl.metadata (2.3 kB)
Collecting scipy==1.9.1 (from root-painter-trainer)
  Using cached scipy-1.9.1.tar.gz (42.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: C:\Users\11966\AppData\Local\Temp\pip-install-rfspuuk6\scipy_c296d934b1194bb6ab46e607b3ce2a46
      Build dir: C:\Users\11966\AppData\Local\Temp\pip-install-rfspuuk6\scipy_c296d934b1194bb6ab46e607b3ce2a46\.mesonpy-6_upyno5\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.1
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

      ..\..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running "icl " gave "[WinError 2] The system cannot find the file specified"
      Running "cl /?" gave "[WinError 2] The system cannot find the file specified"
      Running "cc --version" gave "[WinError 2] The system cannot find the file specified"
      Running "gcc --version" gave "[WinError 2] The system cannot find the file specified"
      Running "clang --version" gave "[WinError 2] The system cannot find the file specified"
      Running "clang-cl /?" gave "[WinError 2] The system cannot find the file specified"
      Running "pgcc --version" gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\11966\AppData\Local\Temp\pip-install-rfspuuk6\scipy_c296d934b1194bb6ab46e607b3ce2a46\.mesonpy-6_upyno5\build\meson-logs\meson-log.txt
      + meson setup --native-file=C:\Users\11966\AppData\Local\Temp\pip-install-rfspuuk6\scipy_c296d934b1194bb6ab46e607b3ce2a46\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Users\11966\anaconda3 C:\Users\11966\AppData\Local\Temp\pip-install-rfspuuk6\scipy_c296d934b1194bb6ab46e607b3ce2a46 C:\Users\11966\AppData\Local\Temp\pip-install-rfspuuk6\scipy_c296d934b1194bb6ab46e607b3ce2a46\.mesonpy-6_upyno5\build
      Traceback (most recent call last):
        File "C:\Users\11966\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\11966\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11966\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 969, in get_requires_for_build_wheel
          with _project(config_settings) as project:
        File "C:\Users\11966\anaconda3\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 948, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\11966\anaconda3\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 777, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 682, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 713, in _configure
          self._meson(
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 696, in _meson
          return self._proc('meson', *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11966\AppData\Local\Temp\pip-build-env-qz58rrki\overlay\Lib\site-packages\mesonpy\__init__.py", line 691, in _proc
          subprocess.check_call(list(args))
        File "C:\Users\11966\anaconda3\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\11966\\AppData\\Local\\Temp\\pip-install-rfspuuk6\\scipy_c296d934b1194bb6ab46e607b3ce2a46\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Users\\11966\\anaconda3', 'C:\\Users\\11966\\AppData\\Local\\Temp\\pip-install-rfspuuk6\\scipy_c296d934b1194bb6ab46e607b3ce2a46', 'C:\\Users\\11966\\AppData\\Local\\Temp\\pip-install-rfspuuk6\\scipy_c296d934b1194bb6ab46e607b3ce2a46\\.mesonpy-6_upyno5\\build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Abe404** [comment]
I notice that the issue has been closed. Did you find a solution for this?

**Comment by ExtroT** [comment]
Yes, I used Cuda 11.7, and the problem seems resolved. The problem was found in both 11.8 and 12.5.
