### ISSUE TITLE
Open existing project | Cannot find file error

### ISSUE THREAD

**Issue by jeremysadkins** [Abe404/root_painter#146]
**Describe the bug**
Hello, when I try to open an existing project, I get a message that says RootPainter cannot find one of my image files. I had messed around with the "specify sync directory" option, but I changed it back to the original (Y:\work\hblab\root_painter_sync).

**To Reproduce**
1. Start RootPainter
2. Click on Open existing project
3. It opens to Y:\work\hblab\root_painter_sync\projects
4. Open T4_roots folder
5. Open T4_roots.seg_proj file
6. Error message appears

**Expected behavior**
The program should start running at this point, with the next image ready for annotation.

**Screenshots**
![image](https://github.com/user-attachments/assets/e6664930-7e10-4ad6-a5d9-21b9e01d8e10)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 0.2.27 

**Additional context**
At some point, I tried to remove images from the datasets folder, but I added them back in. Since then, I have been able to open the project and resume training mode, so I am not sure what has changed.

**Comment by Abe404** [comment]
Hi Jeremy,

It's good to hear from you. 

Thanks for reporting the problem. I suspect something might have gotten misconfigured in your local setup. I'm not sure what yet. 

There's a couple of config files we can check to try to figure out what might be wrong. 
Firstly, in your home folder is a root_painter_settings.json file. This tells RootPainter where to look for the sync directory.
Secondly, there's the project file (.seg_proj). Could you share those files? Or a screenshot showing the relevant parts.

The project file (in the project folder) contains within it the path to the dataset. 

 It might give me a better idea of what might be wrong and why RootPainter can't find the image.

Thanks again for your patience with this. Let me know if you'd like to work through this on a zoom call instead. I'm sure we can get it figured out either way.

Kind regards,
Abraham

**Comment by jeremysadkins** [comment]
Thanks for getting back to me! I hope your summer went well.

I am traveling through Sunday so I will get back to you on Monday with that information or to set up a zoom call.

Thanks again,


Jeremy S. Adkins

(they/them/theirs)

Warnell School of Forestry and Natural Resources
Graduate Assistant | PhD Student



[University of Georgia]

________________________________

**Comment by jeremysadkins** [comment]
Hello again,

I hope you had a restful weekend! Here are the files you requested. If it would be easier to zoom I have time at 3 pm or later on Wednesday and Friday or 3 to 4:30 on Thursday(CET).

My goal is to get this project working again but I would also like to remove 10 images from the project. I don’t know if this is possible.

Thank you for the help!
Jeremy S. Adkins
(they/them)

**Comment by jeremysadkins** [comment]
On second thought, I think I got it!After looking at the files you asked for,  I updated the project file to call the right dataset and then deleted the 10 file names for the files I remobved from the dataset.

Thank you!
Jeremy S. Adkins
(they/them)

From: Jeremy Steven Adkins
Sent: Monday, September 9, 2024 1:17 PM
To: Abe404/root_painter ***@***.***>; Abe404/root_painter ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Abe404/root_painter] Open existing project | Cannot find file error (Issue #146)

Hello again,

I hope you had a restful weekend! Here are the files you requested. If it would be easier to zoom I have time at 3 pm or later on Wednesday and Friday or 3 to 4:30 on Thursday(CET).

My goal is to get this project working again but I would also like to remove 10 images from the project. I don’t know if this is possible.

Thank you for the help!
Jeremy S. Adkins
(they/them)

**Comment by Abe404** [comment]
Glad you got it sorted :)
