### ISSUE TITLE
Manual Brush Size Selection Window Feature Request

### ISSUE THREAD

**Issue by thecrobe** [Abe404/root_painter#19]
Love root painter, I want to paint all the roots. 

One feature I would like to request is a window to manaully select brush size, would be really helpful! 

Best, 

Justin

**Comment by Abe404** [comment]
Thanks Justin! 

I think an option to set brush size manually makes sense. I had some concerns that doing this might discourage users from learning the keyboard shortcuts, which I expect to be faster, but I can always provide a reminder of the keyboard shortcut on the manual brush size selection window. This should also help address another issue, where users find it unclear how to change brush size when opening the client https://github.com/Abe404/root_painter/issues/11

I'll see what I can do and let you know.

Kind regards,
Abraham

**Comment by Abe404** [comment]
The installers are ready and the new version is ready for testing.

There is a new release with this change included. 

https://github.com/Abe404/root_painter/releases/tag/0.2.8
