### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by aunsid** [Abe404/root_painter#2]
Is there a Readme to get this to work and what all dependencies it requires?

**Comment by Abe404** [comment]
Hey!

I'm glad you found this project 👎 

I put some instructions at the end of the paper.

Which is available at:
https://www.biorxiv.org/content/10.1101/2020.04.16.044461v1.full

See:
Supplementary Note 4: Server software setup instructions

I put some requirements files in the painter and trainer directories. I suggest using pip to install them into virtual environments.

I think shifting more of these into a readme is a good idea.

**Comment by Abe404** [comment]
Perhaps the server setup and lung segmentation tutorials could be useful:

If you have a GPU and client are running on the same machine you can skip the bits about sshfs
https://github.com/Abe404/root_painter/blob/master/docs/server_setup_sshfs.md

https://github.com/Abe404/root_painter/blob/master/docs/cxr_lung_tutorial.md

**Comment by Abe404** [comment]
I added some instructions to the (main readme)[https://github.com/Abe404/root_painter/blob/master/README.md]

Please let me know if that helps

**Comment by Abe404** [comment]
@aunsid I will close this now due to inactivity. Feel free to reopen this issue if you have any more questions or feel further documentation is required.
