### ISSUE TITLE
Region Property Crash

### ISSUE THREAD

**Issue by thecrobe** [Abe404/root_painter#22]
Howdy! 

When using the extract region property function I find the root painter app crashes on my computer (server is fine). This seems to happen quite often. Any ideas on how to prevent this?

Thanks, 

Justin

**Comment by thecrobe** [comment]
I found its an image (although a few seem to cause this) that was segmented. I have attatched it here. So grateful for the help! 
![A205_stitched_green](https://user-images.githubusercontent.com/56614237/139841691-7d5f9e3d-80d4-44f1-ae48-4a2bd9c388b2.png)

**Comment by Abe404** [comment]
Thanks! I'm looking into it now.

**Comment by Abe404** [comment]
I was able to reproduce the problem with the file found. Only output so far is "zsh: bus error". Extract length seems to work while extract region properties does not. Will update when I have more details.

**Comment by thecrobe** [comment]
oh glad its not just me! No rush!!! Many many thanks

**Comment by Abe404** [comment]
The problem seems to be with the computation of eccentricity. Is this something you are using? I'm thinking of just removing it in the next version as I don't know anyone who is using it.

**Comment by thecrobe** [comment]
I think its a cool metric but do not know if its the most helpful. The only thing we use it for is to search for outliers when identifying  spores and nodules but obviously this doesn’t help well when we get to large clusters. I think removal would be fine if not too much work.

**Comment by Abe404** [comment]
It turns out that others are also using it, so I will try to find a way to fix the problem and keep eccentricity output.

**Comment by Abe404** [comment]
Hey Justin,

I wasn't able to properly track down the issue in scikit-image, that was causing the bus error but found that the issue went away when pulling the eccentricity computation code into the RootPainter code base (as opposed to calling the scikit-image library).

I have made a new release for you to test which is available here:
https://github.com/Abe404/root_painter/releases/tag/0.2.9

Can you let me know if you are still experiencing the problem with this new version?

Kind regards,
Abraham

**Comment by thecrobe** [comment]
Hi Abraham, 

I just had a chance to try it out and it works fine on the image I sent that gave trouble. It now seems its also acting up for this image interestingly. Cant tell if its the same issue… I attached the segmentation in case you’d like to try. It also is happening with another image but will take time to figure out which one. 

Is a version of the software without the eccentricity an option to use in the meantime, although I have no idea how difficult that is logistically. 

Again so many thanks! 

-Justin

**Comment by Abe404** [comment]
Hi Justin,

OK thanks. I will take a look. I can't see the new segmentation though. Are you sure you attached it?

Kind regards,
Abraham

**Comment by thecrobe** [comment]
Oh I tried to do through email, let me upload here on github!
![A017_stitched_green](https://user-images.githubusercontent.com/56614237/139941890-4d69eec4-688a-4bad-9362-c9e474e7ca15.png)

**Comment by Abe404** [comment]
It seems to be working OK for me. Can you confirm you are running version 0.2.9? If you go the About Menu and then click the RootPainter menu item, you should see that the version is 0.2.9.

Assuming you are running 0.2.9 then there isn't much else I can do to fix the eccentricity error, as I'd need to be able to reproduce it on my machine to work on solving it. I will work on a version that makes the output optional using checkboxes as a temporary solution, so you at least disable the eccentricity output when it causes problems.

**Comment by thecrobe** [comment]
Hmm very odd. Just checked and its 0.2.9. Temporary solution sounds great for now, if I come into any other bugs Ill let you know! 

Justin

**Comment by Abe404** [comment]
Hey Justin,

I think one of the issues with reproducing the problem is that it's related to  the computation / memory requirements of processing these large images.

Your original images have size: 5100 × 6600, which is larger than what I usually test the region properties function on.

I tried doubling the width and height  of your images and now the error comes back reliably.

So I think there are just some limitations to computing the eccentricity of regions in very large images.

I will work on a solution to allow eccentricity output to be disabled, but another option (if you need eccentricity) would be to reduce the resolution of the images.

I will update in an hour or two when I have the new feature.

Kind regards,
Abraham

**Comment by thecrobe** [comment]
Ah yeah we do take quite large and high res images in our lab. We can downsize for sure and that’s good to know for out 1 mil by 1 mil pixel images I haven’t tried out yet. Great to find this out. 

Many thanks!

Justin

**Comment by Abe404** [comment]
OK I updated the installer for the latest release (0.2.9) to include the option to disable eccentricity output. So you have the option of working with your extremely large images if you only want the other region properties.

See inserted screenshot:
<img width="659" alt="region_props_screenshot" src="https://user-images.githubusercontent.com/376295/139952163-ef7852e0-3072-4d73-8a26-5d286bf74944.png">

The updated installer is available from:
https://github.com/Abe404/root_painter/releases/tag/0.2.9

**Comment by Abe404** [comment]
When you get chance to test this, can you let me know if extract regions properties works for all of your images now?

**Comment by thecrobe** [comment]
Works perfectly for all of the images. Super thankful!
