### ISSUE TITLE
ubuntu (20)  Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by Abe404** [Abe404/root_painter#41]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Comment by Abe404** [comment]
Reverting to pyinstaller 4.8 seemed to fix the problem. See:
https://github.com/Abe404/root_painter/commit/48ebcc628e62e1070423e5524afed17400a1b608

With CI run here:
https://github.com/Abe404/root_painter/actions/runs/3001359879

**Comment by andreped** [comment]
See this:
https://github.com/dbouget/Raidionics/blob/master/main.py#L20

**Comment by Abe404** [comment]
Thanks! I tried adding similar code using PyQt5 (instead of PySide). Following the docs in your link i got back to this: 
https://github.com/pyqt/python-qt5/issues/2

I added the change to the main file in RootPainter. You can see what was changed in this commit:
https://github.com/Abe404/root_painter/commit/208dd14c34b6e19b00b94355b1d591ce2e70cced

But it did not appear to fix the problem. It appears the issue could be happening somewhere else (the print statement you can see in the above commit did not appear in the output of the CI process). I suspect it is related to pyqtgraph.
