### ISSUE TITLE
Image skip to start/to end/to index function 

### ISSUE THREAD

**Issue by geezacoleman** [Abe404/root_painter#59]
This is just a feature request - I can't seem to find if this is already implemented.

I've been trying to get some screenshots for publications I'm using RootPainter for and wanted to skip back to the first few images I've used to show the annotation approach/progress. Is there any easier way to do it than pressing back and waiting for each image to load? 

If not it would be handy to have a 'skip to index' or 'skip to start' option for this kind of purpose.

**Comment by Abe404** [comment]
The easiest way to do this right now is with the metrics plot.

With the project open, go to the extras menu and view metrics plot. The click on the image point in the metrics plot and it will take you to the image in the viewer.

**Comment by Abe404** [comment]
I appreciate the current way to do it is not completely intuitive to users who aren’t already familiar with the metrics plot.

I’ve considered making an option to navigate /skip to different images using a more intuitive and more easily discoverable menu option. My concern is that it might encourage users to work through the images non-sequentially leading to deviation from the current corrective annotation protocol (and subsequent inefficiencies etc). Working through the images non-sequentially would also make the metrics plot make less sense. What do you think? Perhaps I should just add the navigation options and then we can see if it leads to problems? Perhaps users would still work through the images sequentially.

**Comment by geezacoleman** [comment]
Ah I see - haven't used that before, quite a neat tool. Does make it easy to move through to the image you want to find. 

Understand the hesitation around enabling a work around for the corrective annotation protocol, for my purposes your solution works just fine. Perhaps the navigation could simply be another option under 'Extras' or another drop down where a user would need to enter an image index to move there. At least it would make it slightly more out the way than having it under each image.

**Comment by Abe404** [comment]
As the metrics plot is working OK for you I will stick to that. There's a bunch of side-effects/other problems that could come out of a navigate to image by index option, so I will hold off implementing it for now. 

I created an FAQ and added this question: https://github.com/Abe404/root_painter/blob/master/docs/FAQ.md
