### ISSUE TITLE
instructions folder empty

### ISSUE THREAD

**Issue by jmicciulla** [Abe404/root_painter#75]
When starting the server the command looks for instructions in drive_rp_sync/instructions, but the instructions folder is empty and the command cannot move past this step to run the rest of initial setup following Root Painter Setup in Colab. 

<img width="1295" alt="Screen Shot 2023-01-12 at 11 54 12 AM" src="https://user-images.githubusercontent.com/46489324/212157398-89e178e2-f0a7-417b-ae20-827d573f0682.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey v12.4  
 - Browser: Chrome
 - Version: 108.0.5359.124

**Comment by Abe404** [comment]
Actually everything is working OK. You leave this cell running (just as you see it). 

Once you open the client and start looking at images it will start generating instructions. Then you should see more output in this cell (right now it is waiting for instructions from the client).

There's some information further down the page that says **What should it look like?** that's supposed to make it clear that what you have done is correct, but it seems that it was not very visible. I've moved it a bit further up.

**Comment by Abe404** [comment]
I'm going to close this issue for now because it seems everything is working OK. Next step is just to setup  (install) the client and start viewing/annotation the images and then start training.

**Comment by Abe404** [comment]
But do still let me know if you get stuck again. I will do what I can to help :)
