### ISSUE TITLE
wrong dataset message should mention option to respecify the sync directory

### ISSUE THREAD

**Issue by Abe404** [Abe404/root_painter#90]

**Comment by Abe404** [comment]
Sometimes users want to start working with data in a different sync directory. They are not necessarily aware of how to update the sync directory (the option is in the extras menu).

When they create a project they receive a warning that the dataset they are using is not in the right sync directory (it's in the old sync directory and not the new one). At this point we could inform them that there may be an issue with the location of the specified sync directory and that they can update the location of the specified sync directory using the option from the extras menu.

**Comment by geezacoleman** [comment]
Just had this issue with a student - error message said datasets were in the wrong directory but took us a while to figure out why. Only upon reading this issue did I realise that you had to specify the sync directory from the Extras menu.

**Comment by Abe404** [comment]
Thanks for reporting this. I realise this sync directory stuff can be a bit of a hassle and I'd like to make it easier for users to fix it when it goes wrong (or for it to just not go wrong in the first place).

I've implemented the fix as described in this issue (see inserted screenshot):

<img width="433" alt="error_message_longer" src="https://user-images.githubusercontent.com/376295/225936615-32c8425b-b5ea-4d35-b639-c3a8928d0f71.png">

This is in the master branch but is not in a release yet so I will leave this issue open for now.

I will also keep an eye out for other areas where I can make this sync directory management more intuitive.

**Comment by geezacoleman** [comment]
Thanks for adding this extra text to the error message, would definitely solve the issue quite quickly.

**Comment by Abe404** [comment]
https://github.com/Abe404/root_painter/releases/tag/0.2.27
